spring.application.name=shoerental
spring.data.mongodb.uri=mongodb+srv://admin:MongoDB2024@cluster0.qychv5a.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=shoerental
